### PR TITLE
Correct line comments and remove block comments

### LINKED ISSUE #1: Shortcut to comment out a line uses wrong comment syntax
When using the keyboard shortcut `Ctrl + /` after installing the extension, the current line is commented with `//` instead of `#`, ie:

```
// ENV_VAR2=test2
# instead of:
# ENV_VAR2=test2
```

### PR DESCRIPTION
**Pull request by gilest**
Fixes #1

I don't think .env supports block comments either...

### CODE REVIEW

**Comment by gilest** [comment]
@WellerQu please review 👋

**Comment by dumptyd** [comment]
This would be nice to have!

**Comment by skplunkerin** [comment]
PLEASE! ❤️  I was just about to create a PR doing exactly this

**Comment by WellerQu** [comment]
> PLEASE! ❤️ I was just about to create a PR doing exactly this

thanks. I will re-publish a new version to market.

**Pull request merged**
